# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

ulimit -c 5000

#
# Use custom startup scripts in ~/.bash.d
#
#CUSTOMENV=~/.bash.d/bash.env
CUSTOMENV=$(mktemp --tmpdir=/dev/shm bash_env.XXXXXXXXXX)
cat >"$CUSTOMENV" <<_EOF_
# THIS FILE IS AUTOMATICALLY GENERATED BY ~/.bashrc.
# DO NOT EDIT THIS FILE. CHANGES TO STARTUP PROFILES
# GO INTO ~/.bash.d NOT $CUSTOMENV

# File Generated on $(date)

_EOF_

find -L ~/.bash.d/$(hostname) -type f -print0 | sort -z |while read -d $'\0' file
do
	echo -ne "\n#\n# FILE: $file\n#\n\n"
	cat "$file"
done >> "$CUSTOMENV"

source "$CUSTOMENV"
/bin/rm "$CUSTOMENV"
