# .bashrc

# Took this test for interactive shell from gentoo /etc/shel/.bashrc
# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
        # Shell is non-interactive.  Be done now!
        return
fi

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

ulimit -c 5000

# ~/bin has not been added to PATH yet, so need to specify full path to
# MyPersonalUpdate
CUSTOMENV=$(~/bin/MyProfileUpdate -sq)

[[ -f "$CUSTOMENV" ]] && source "$CUSTOMENV"
