# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

ulimit -c 5000

# ~/bin has not been added to PATH yet, so need to specify full path to
# MyPersonalUpdate
CUSTOMENV=$(~/bin/MyProfileUpdate -sq)

[[ -f "$CUSTOMENV" ]] && source "$CUSTOMENV"
