# lxde is default
session=${1:-lxde}

# To create ConsoleKit session.
consolekit="ck-launch-session dbus-launch --sh-syntax --exit-with-session"

case $session in
    awesome           ) exec $consolekit awesome;;
    bspwm             ) exec $consolekit bspwm;;
    catwm             ) exec $consolekit catwm;;
    cinnamon          ) exec $consolekit cinnamon-session;;
    dwm               ) exec $consolekit dwm;;
    enlightenment     ) exec $consolekit enlightenment_start;;
    ede               ) exec $consolekit startede;;
    evilwm            ) exec $consolekit evilwm;;
    fluxbox           ) exec $consolekit startfluxbox;;
    gnome             ) exec $consolekit gnome-session;;
    gnome-classic     ) exec $consolekit gnome-session --session=gnome-classic;;
    i3|i3wm           ) exec $consolekit i3;;
    icewm             ) exec $consolekit icewm-session;;
    jwm               ) exec $consolekit jwm;;
    kde               ) exec $consolekit startkde;;
    lxde              ) exec $consolekit startlxde;;
    lxqt              ) exec $consolekit startlxqt;;
    mate              ) exec $consolekit mate-session;;
    monster|monsterwm ) exec $consolekit monsterwm;;
    notion            ) exec $consolekit notion;;
    openbox           ) exec $consolekit openbox-session;;
    unity             ) exec $consolekit unity;;
    xfce|xfce4        ) exec $consolekit startxfce4;;
    xmonad            ) exec $consolekit xmonad;;
    # No known session, try to run it as command
    *) exec $consolekit $1;;
esac
